spring:
  redis:
    host: ${service.redis.host:192.168.0.213}
    database: 3

security:
  oauth2:
    resource:
      filter-order: 3

service:
  oauth2:
    signing-key: iot
    token-store: redis

logging:
  level:
    org.springframework.security: DEBUG